
[functions.ai-todo-breakdown]
enabled = true
verify_jwt = true
import_map = "./functions/ai-todo-breakdown/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-todo-breakdown/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-todo-breakdown/*.html" ]

[functions.ai-create-todo]
enabled = true
verify_jwt = true
import_map = "./functions/ai-create-todo/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-create-todo/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-create-todo/*.html" ]
